# Generated by Django 5.2.4 on 2025-08-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctorcheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='ชื่อผู้ป่วย')),
                ('appointment_time', models.DateTimeField(verbose_name='วันเวลานัดหมาย')),
                ('status', models.CharField(choices=[('pending', 'รอพบแพทย์'), ('completed', 'เสร็จสิ้น'), ('canceled', 'ยกเลิก')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='แพทย์')),
            ],
        ),
    ]
