# Generated by Django 4.2.11 on 2025-10-08 12:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='อายุ (ปี)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ประวัติการแพ้ยา/อาหาร'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='ระยะเวลา'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่น ๆ')], max_length=10, null=True, verbose_name='เพศ'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ส่วนสูง (ซม.)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรผู้ป่วย'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='บัญชีผู้ใช้'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='อาการเบื้องต้น'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='underlying_disease',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='โรคประจำตัว'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='น้ำหนัก (กก.)'),
        ),
    ]
