# Generated by Django 4.2.11 on 2025-10-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_age_appointment_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_user',
        ),
    ]
