# Generated by Django 5.2.4 on 2025-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อแพทย์')),
                ('specialty', models.CharField(max_length=100, verbose_name='สาขา')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='เบอร์ติดต่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
            ],
        ),
    ]
