# Generated by Django 4.2.11 on 2025-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctorcheckin',
            name='checkin_at',
            field=models.DateTimeField(verbose_name='วันที่และเวลาเข้าทำงาน'),
        ),
    ]
