# Generated by Django 4.2.11 on 2025-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcheckin',
            name='checkin_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่เข้าทำงาน'),
        ),
    ]
